name:                tidal-stack
version:             0.1.0.0
github:              "tonyday567/tidal-stack"
license:             BSD3
author:              "Tony Day"
maintainer:          "tonyday567@gmail.com"
copyright:           "Tony Day (c) 2017"

extra-source-files:
- readme.md

description: stack-friendly wrapper for tidal

dependencies:
- base >= 4.7 && < 5

executables:
  tidal-boot-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
      - tidal
